### ISSUE TITLE
Fatal error with submission

### ISSUE THREAD

**Issue by aclapinpepin** [saasbook/rag#54]
Hello all.

I get this message since a week now trying to upload hw4. I removed factory_girl completely in my homework now using fixtures as it was discussed in the forum.

```
Your submission was recorded at 2015-12-08 20:51:01 +0000 : submission is late and scaled by 0.75
Score: 0/100
There was a fatal error with your submission. It either timed out or caused an exception.
```

I just get that message without any other backtrace to identify the error.

Any help would be greatly appreciated!

**Comment by bill-auger** [comment]
this issue is also noted on pivotal --> https://www.pivotaltracker.com/n/projects/1429516/stories/109570418

**Comment by goatold** [comment]
I've got the same problem, even after I removed my entire spec dir when I submit.

**Comment by bill-auger** [comment]
i just got the following response from the course admin

>  these errors are often due to the structure of the zip archive - the students need to ensure they have things inside a directory as per the homework instructions. It is of course possible that there are other causes, but we don't have good reporting on the grader, and can't investigate unless we have a copy of the students submission - feel free to attach to this ticket

so check to ensure that the structure of the zip archive according to the the homework instructions - and if you cant find a problem drop your zip file here and ill pass it on

**Comment by goatold** [comment]
@bill-auger Thanks for your feedback. I double checked the zip structure. It should comply with the instructions. 
And I cannot attach my zip file here. So I put it in my github
https://github.com/goatold/docShare/blob/master/hw4.ZIP

**Comment by aclapinpepin** [comment]
@bill-auger Thanks as well for you feedback. My zip structure should also comply with the instructions. Here is mine:
https://www.dropbox.com/s/i1ac6lzad8rjrmi/hw4.zip?dl=0

**Comment by bill-auger** [comment]
@aclapinpepin
i was able to get your homework past the fatal error simply by renaming it from hw4.ZIP to hw4.zip

@goatold

you also will want to ensure your zip file is name hw4.zip and not hw4.ZIP - but yours had more issues
i was able to get your homework past the fatal error by replacing your db/ and config/ directories with the ones from the default skeleton repo

one of the casues of the error was your create_movies migration - you did not need to modify the default create_movies migration this was  - also several of the files in config/ are quite different from the homework skeleton and im fairly sure the only file in the config/ directory that needs to be modified is routes.rb 

so i would suggest replacing your db/ and config/ directories with the ones from the default skeleton repo as i did - and adding back your add_director mirgation and routes.rb

**Comment by goatold** [comment]
@bill-auger Thanks a lot for debugging my hw4. I did everything from scratch instead of clone from the skeleton. Anyways, it can pass part of the grader after I clone from the hw-bdd-tdd-cycle repo

My rspec still fails with grader. But my execution on c9 went well.

================== Grader output ===============
 /home/ubuntu/.rvm/rubies/ruby-2.2.2/bin/ruby -I/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib:/home/ubuntu/.rvm/gems/ruby-2.2.2/gems/rspec-support-3.3.0/lib /home/ubuntu/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed


================== c9 local output ===============
rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

MoviesController
  GET #index
    assigns all movies as @movies
    orders all movies as @movies
  GET #similar
    assigns all movies of the same director as @movies
    redirect_to index page when director is nil
  GET #show
    assigns the requested movie as @movie
  GET #new
    response empty
  GET #edit
    assigns the requested movie as @movie
  POST #create
    with valid params
      creates a new Movie
      assigns a newly created movie as @movie
      redirects to the created movie
  PUT #update
    with valid params
      updates the requested movie
      assigns the requested movie as @movie
      redirects to the movie
  DELETE #destroy
    destroys the requested movie
    redirects to the movies list

Movie
  query movies of the same direcotr as a given movie
    return a movie list of that director if director not nil
    return nil if director is nil

Movies
  GET /movies
    movies path works!

MoviesController
  routing
    routes to #index
    routes to #new
    routes to #show
    routes to #edit
    routes to #similar
    routes to #create
    routes to #update via PUT
    routes to #update via PATCH
    routes to #destroy

Finished in 0.74083 seconds (files took 9.74 seconds to load)
27 examples, 0 failures

Coverage report generated for RSpec to /home/ubuntu/hw4/coverage. 48 / 48 LOC (100.0%) covered.
===================================

link to updated hw4.zip
https://github.com/goatold/docShare/blob/master/hw4.zip

**Comment by aclapinpepin** [comment]
Thanks @bill-auger for the help on this issue. I can now submit the homework but the grader only runs the cucumber tests.

Since everything is working locally and since I reached the 75% needed to pass the course, I won't try to solve the problems of the specs not being run.

Looking forward to part 2 of this course next year!

**Comment by bill-auger** [comment]
@goatold 
i can not open that file - ive tried with two different archive tools - which program are you using to create the zip file ? is it something that was pre-installed in cloud9 ?

**Comment by goatold** [comment]
@bill-auger 
Sorry for the inconvenience. I re-zip it and put it on Google drive
https://drive.google.com/file/d/0BzE2SPk8YvTwdnVFT1pBc1AyX3c/view?usp=sharing

Thanks a lot for your time on this. Echo aclapinpepin's comment, I don't need to get a higher score either. But I do want to learn what's wrong.

**Comment by tansaku** [comment]
@bill-auger did we ever work this out satisfactorily?

**Comment by bill-auger** [comment]
yes - there were multiple students with different issues - i got to the root of the OP's problem and was able to solve the others but without knowing the root cause exactly - the OP's only problem was that the filename of his archive upload was hw4.ZIP and was corrected simply by renaming to hw4.zip - the second student's problem was that he had unnecessarily modified some of the skeleton files under db/ and config/ and this somehow caused the grader to reject - the findings are posted above - i will re-post them here

> ### aclapinpepin -
> i was able to get your homework past the fatal error simply by renaming it from hw4.ZIP to hw4.zip
> 
> ### goatold -
> you also will want to ensure your zip file is name hw4.zip and not hw4.ZIP - but yours had more issues
> i was able to get your homework past the fatal error by replacing your db/ and config/ directories with the ones from the default skeleton repo
> 
> one of the casues of the error was your create_movies migration - you did not need to modify the default create_movies migration this was - also several of the files in config/ are quite different from the homework skeleton and im fairly sure the only file in the config/ directory that needs to be modified is routes.rb
> 
> so i would suggest replacing your db/ and config/ directories with the ones from the default skeleton repo as i did - and adding back your add_director mirgation and routes.rb - remember to migrate down first and then migrate up and reseed
>
